-- ola

-- create schema dbex;

drop table dbex.cidades;

create table if not exists dbex.cidades(
    id int generated by default as identity primary key,
    -- OU id int generated always as identity primary key,
    nome varchar(150) not null,
    estado char(2) not null default 'RN'
);

create table if not exists dbex.localizacoes(
    id int generated always as identity,
    id_cidade int not null,
    latitude float not null,
    longitude float not null,

    constraint localizacoes_pk primary key (id),
    constraint localizacoes_cidade_fk foreign key (id_cidade) references dbex.cidades(id)
);

create table if not exists dbex.localizacoes(
    id int generated always as identity,
    id_cidade int not null,
    temp_min int not null,
    temp_max int not null,
    precip_pluvio float null default '0.0',
    data_coleta timestamp not null,

    constraint tempos_pk primary key (id),
    constraint tempos_cidade_fk foreign key (id_cidade) references dbex.cidades(id)
);

-- select octect_length('olá'::varchar(10);

-- create type dia_da_semana as enum
--     ('Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab');
